spring:
  profiles:
      active:
        - second
        - EN
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl

---

guru:
  username: YmlProdUserName
  password: YmlProdPw
  jdbcurl: YmlProdUrl
spring:
  config:
    activate:
      on-profile: prod